-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 22:12:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MqttTemperatur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MqttTemperatur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MqttTemperatur` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `MqttTemperatur` ;

-- -----------------------------------------------------
-- Table `MqttTemperatur`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MqttTemperatur`.`Rooms` (
  `RoomID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`RoomID`),
  UNIQUE INDEX `ID_UNIQUE` (`RoomID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MqttTemperatur`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MqttTemperatur`.`Topics` (
  `TopicID` INT NOT NULL AUTO_INCREMENT,
  `Topic` VARCHAR(255) NULL,
  `Rooms_ID` INT NOT NULL,
  PRIMARY KEY (`TopicID`, `Rooms_ID`),
  INDEX `fk_Topics_Rooms1_idx` (`Rooms_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`TopicID` ASC) VISIBLE,
  CONSTRAINT `fk_Topics_Rooms1`
    FOREIGN KEY (`Rooms_ID`)
    REFERENCES `MqttTemperatur`.`Rooms` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MqttTemperatur`.`Temperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MqttTemperatur`.`Temperature` (
  `TemperatureID` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `Temperature` DECIMAL(5) NULL,
  `Rooms_ID` INT NOT NULL,
  PRIMARY KEY (`TemperatureID`, `Rooms_ID`),
  INDEX `fk_Temperature_Rooms1_idx` (`Rooms_ID` ASC) VISIBLE,
  UNIQUE INDEX `idTemperature_UNIQUE` (`TemperatureID` ASC) VISIBLE,
  CONSTRAINT `fk_Temperature_Rooms1`
    FOREIGN KEY (`Rooms_ID`)
    REFERENCES `MqttTemperatur`.`Rooms` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Client' IDENTIFIED BY 'password';

GRANT ALL ON `MqttTemperatur`.* TO 'Client';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
